const express = require("express");
const router = express.Router();
const fs = require("fs");
const path = require("path");
const { checkRole } = require("../middleware/role");
const { PDFDocument, rgb } = require("pdf-lib");

// 1️⃣ Show list of files in generated/
router.get("/reports/review/files", (req, res) => {
  const folderPath = path.join(__dirname, "../reports/generated");

  fs.readdir(folderPath, (err, files) => {
    if (err) return res.status(500).json({ message: "Error reading files" });

    res.json(files);
  });
});

// 2️⃣ Serve PDF preview
router.get("/reports/review/file/:filename", checkRole("Reviewer"), (req, res) => {
  const { filename } = req.params;
  const filePath = path.join(__dirname, "../reports/generated", filename);

  if (!fs.existsSync(filePath))
    return res.status(404).json({ message: "File not found" });

  res.sendFile(filePath);
});

// 3️⃣ Sign (review) and move file to reviewed/
router.post("/review/sign", checkRole("Reviewer"), async (req, res) => {
  const { filename } = req.body;
  const reviewer = req.user?.username;

  console.log("Reviewer value:", reviewer);

  const oldPath = path.join(__dirname, "../reports/generated", filename);
  const newPath = path.join(__dirname, "../reports/reviewed", filename);

  if (!fs.existsSync(oldPath)) {
    return res.status(404).json({ message: "Original file not found" });
  }

  try {
    const existingPdfBytes = fs.readFileSync(oldPath);
    const pdfDoc = await PDFDocument.load(existingPdfBytes);
    const pages = pdfDoc.getPages();
    const reviewDate = new Date().toLocaleString();
    const reviewLine = `Reviewed by: ${reviewer} on ${reviewDate}`;

    pages.forEach((page) => {
      page.drawText(reviewLine, {
        x: 30, // Adjust to align with "Generated by"
        // y: 45, // Same Y as the original footer
        y: 35,
        size: 8, // Match size
        color: rgb(0.4, 0.4, 0.4), // Match gray color
      });
    });



    const signedPdfBytes = await pdfDoc.save();
    fs.writeFileSync(newPath, signedPdfBytes);

    fs.unlinkSync(oldPath); // delete original
    res.json({ message: "Report reviewed and moved" });
  } catch (error) {
    console.error("Error signing PDF:", error);
    res.status(500).json({ message: "Failed to sign and move report" });
  }
});

module.exports = router;


