// src/components/Reports.jsx
import React, { Component } from "react";
import axios from "axios";

class Reports extends Component {
  state = {
    reports: [],
    loading: true,
  };

  componentDidMount() {
    axios
      .get("http://localhost:5000/api/reports")
      .then((res) => {
        this.setState({ reports: res.data, loading: false });
      })
      .catch((err) => {
        console.error("Error fetching reports:", err);
        this.setState({ loading: false });
      });
  }

  render() {
    const { reports, loading } = this.state;

    return (
      <div className="container">
        <h2>📋 Reports</h2>
        {loading ? (
          <p>Loading...</p>
        ) : (
          <table border="1" cellPadding="10">
            <thead>
              <tr>
                <th>ID</th>
                <th>Report Name</th>
                <th>Generated By</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Created At</th>
              </tr>
            </thead>
            <tbody>
              {reports.map((report) => (
                <tr key={report.ReportID}>
                  <td>{report.ReportID}</td>
                  <td>{report.ReportName}</td>
                  <td>{report.GeneratedBy}</td>
                  <td>{report.StartDate}</td>
                  <td>{report.EndDate}</td>
                  <td>{new Date(report.CreatedAt).toLocaleString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    );
  }
}

export default Reports;